# Generated by Django 5.2 on 2026-06-09 06:40

import django.core.validators
import django.db.models.deletion
import invest.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('national_id_no', models.DecimalField(decimal_places=0, help_text='Enter National Identification Number in the format 35033637', max_digits=8, primary_key=True, serialize=False, unique=True, validators=[invest.validators.validate_kenyan_id])),
                ('email_address', models.EmailField(help_text='Please Enter Investor Email Address', max_length=200)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(help_text='Enter phone number in the format 0798073204 or +254798073404', max_length=13, validators=[invest.validators.validate_kenyan_phone_number])),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='System_User',
            fields=[
                ('username', models.CharField(help_text='Enter a valid Username', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password_hash', models.CharField(help_text='Enter a valid password', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.assetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.system_user')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.asset')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
            ],
        ),
        migrations.CreateModel(
            name='TradeIssue',
            fields=[
                ('issue_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('FAILED_ORDER', 'FAILED_ORDER'), ('WRONG_PRICE', 'WRONG_PRICE'), ('MISSING_FUNDS', 'MISSING_FUNDS'), ('OTHER', 'OTHER')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.trade')),
            ],
        ),
        migrations.CreateModel(
            name='TradeResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolver', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RESOLVED', 'RESOLVED'), ('REJECTED', 'REJECTED')], max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(auto_now=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invest.tradeissue')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('FAILED_TRANSACTION', 'FAILED_TRANSACTION'), ('WRONG_PRICE', 'WRONG_PRICE'), ('MISSING_FUNDS', 'MISSING_FUNDS'), ('OTHER', 'OTHER')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_buy_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.asset')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
            ],
            options={
                'unique_together': {('investor', 'asset')},
            },
        ),
    ]
