# Generated by Django 5.2 on 2026-07-06 16:16

import django.core.validators
import django.db.models.deletion
import invest.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Please Enter Interest Rate', max_digits=5)),
                ('liquidity', models.DecimalField(decimal_places=2, help_text='Please Enter Liquidity', max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('national_id_no', models.DecimalField(decimal_places=0, help_text='Enter National Identification Number in the format 35033637', max_digits=8, primary_key=True, serialize=False, unique=True, validators=[invest.validators.validate_kenyan_id])),
                ('email_address', models.EmailField(help_text='Please Enter Investor Email Address', max_length=200)),
                ('username', models.EmailField(help_text='Enter a valid Username', max_length=200, unique=True)),
                ('first_name', models.CharField(help_text='Enter Your First Name', max_length=150)),
                ('last_name', models.CharField(help_text='Enter Your Last Name', max_length=150)),
                ('phone_number', models.CharField(help_text='Enter phone number in the format 0798073204 or +254798073404', max_length=15, validators=[invest.validators.validate_kenyan_phone_number])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidityPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_available', models.DecimalField(decimal_places=2, default=100000, help_text='Please Enter Total Available Amount', max_digits=15)),
                ('total_borrowed', models.DecimalField(decimal_places=2, default=0, help_text='Please Enter Total Amount Borrowed', max_digits=15)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, help_text='Please Enter Total Amount Invested', max_digits=15)),
                ('total_collateral', models.DecimalField(decimal_places=2, default=0, help_text='Please Enter Total Collateral Amount', max_digits=15)),
                ('current_interest_rate', models.DecimalField(decimal_places=2, default=10, help_text='Please Enter Current Interest Rate', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_code', models.CharField(help_text='Please Enter Stock Code', max_length=20, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(help_text='Please Enter Stock Name', max_length=200)),
                ('shares', models.IntegerField(help_text='Enter Number of Available Shares')),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Enter Price per Share', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='System_User',
            fields=[
                ('username', models.CharField(help_text='Enter a valid Username', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password_hash', models.CharField(help_text='Enter a valid password', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Please Enter Amount Invested', max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Please Enter Interest Rate for Investment', max_digits=5)),
                ('duration_days', models.IntegerField()),
                ('amount_accrued', models.DecimalField(decimal_places=2, default=0, help_text='Please Enter Acrued Amount', max_digits=15)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(help_text='Please Enter Investor Email Address', on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, help_text='Please Enter Principal Amount', max_digits=15)),
                ('collateral', models.DecimalField(decimal_places=2, help_text='Please Enter Collateral Amount', max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Please Enter Interest Rate', max_digits=5)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Please Enter Amount Due', max_digits=15)),
                ('duration_days', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('borrower', models.ForeignKey(help_text='Please Select Investor', on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('average_buy_price', models.DecimalField(decimal_places=2, help_text='Please Enter Average Buy Price', max_digits=15)),
                ('investor', models.ForeignKey(help_text='Please Select Investor', on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
                ('stock', models.ForeignKey(help_text='Please Select Stock', on_delete=django.db.models.deletion.CASCADE, to='invest.stock')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.system_user')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], help_text='Please Select Trade Type', max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Please Enter Trade Price', max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(help_text='Please Select Investor', on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
                ('stock', models.ForeignKey(help_text='Please Select Stock', on_delete=django.db.models.deletion.CASCADE, to='invest.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, help_text='Please Enter Available Wallet Balance', max_digits=15)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=0, help_text='Please Enter Locked Balance', max_digits=15)),
                ('invested_amount', models.DecimalField(decimal_places=2, default=0, help_text='Please Enter Investement Balance', max_digits=15)),
                ('borrowed_balance', models.DecimalField(decimal_places=2, default=0, help_text='Please Enter Borrowed Balance', max_digits=15)),
                ('collateral_balance', models.DecimalField(decimal_places=2, default=0, help_text='Please Enter Collateral Balance', max_digits=15)),
                ('investor', models.ForeignKey(help_text='Please Enter Investor Email Address', on_delete=django.db.models.deletion.CASCADE, to='invest.investor')),
            ],
        ),
    ]
